[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
restartPolicy = "always"
maxRetries = 3

[env]
PYTHON_VERSION = "3.11" 