[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[env]
PYTHON_VERSION = "3.11" 